### ISSUE TITLE
o and O commands performing normal VIM functions

### ISSUE THREAD

**Issue by erahhal** [ryanss/vim-hackernews#16]
When o and O are typed, VIM goes into insert mode instead of opening the link.  Perhaps another plugin is interfering.  My installed plugins:

```
Bundle 'gmarik/vundle'         
Bundle 'tpope/vim-fugitive'    
Bundle 'Lokaltog/vim-easymotion'
Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}
Bundle 'wincent/Command-T'     
Bundle 'mustache/vim-mode'     
Bundle 'groenewege/vim-less'   
Bundle 'juvenn/mustache.vim'   
Bundle 'Shutnik/jshint2.vim'   
Bundle 'scrooloose/nerdtree'   
Bundle 'jistr/vim-nerdtree-tabs' 
Bundle 'pthrasher/conqueterm-vim' 
Bundle 'airblade/vim-gitgutter' 
Bundle 'bling/vim-airline'     
Bundle 'tpope/vim-sleuth'      
Bundle 'scrooloose/syntastic'  
Bundle 'mbbill/undotree'       
Bundle 'altercation/vim-colors-solarized' 
Bundle 'hlissner/vim-multiedit' 
Bundle 'majutsushi/tagbar'     
Bundle 'mileszs/ack.vim'       
Bundle 'tyok/nerdtree-ack'     
Bundle 'vim-scripts/DirDiff.vim'
Bundle 'plasticboy/vim-markdown'
Bundle 'christoomey/vim-tmux-navigator'
Bundle 'wavded/vim-stylus'     
Bundle 'jelera/vim-javascript-syntax'
Bundle 'pangloss/vim-javascript'
Bundle 'nathanaelkane/vim-indent-guides'
Bundle 'Raimondi/delimitMate'  
Bundle 'marijnh/tern_for_vim'
Bundle 'tikhomirov/vim-glsl'
Bundle 'vim-scripts/utl.vim'   
Bundle 'tpope/vim-repeat'      
Bundle 'tpope/vim-speeddating' 
Bundle 'mattn/calendar-vim'    
Bundle 'vim-scripts/SyntaxRange'
Bundle 'mhinz/vim-hugefile'    
Bundle 'ryanss/vim-hackernews' 
Bundle 'L9'
Bundle 'FuzzyFinder'           
```

**Comment by ryanss** [comment]
It's not working because you have `filetype off` near the top of your vimrc, which is required for Vundle to load plugins. However, you never turn it back on. I will make a change to the vim-hackernews plugin to force `filetype plugin on` to avoid this problem but I'm surprised some of your other plugins aren't broken due to this. 

`filetype plugin on` automatically loads scripts from `ftplugin` directories in your vim `runtimepath` when you load that type of file. Read more about it with `:help filetype-plugin`. The mappings for `o` and `O` in vim-hackernews are located in `ftplugin/hackernews.vim` and the buffer that opens to show the top stories is named `.hackernews` so that the filetype plugins for `hackernews` are loaded when that buffer opens. This is why those keys have not been remapped for you. You have the line in your vimrc but it is commented out.
