### ISSUE TITLE
Is adding a save current buffer function appropriate and acceptable?

### ISSUE THREAD

**Issue by eduOS** [ryanss/vim-hackernews#33]
I'd like to save the article I like while reading, so I just mapped it as:

nnoremap <buffer> s :silent :w my_direc/.md

Is it acceptable? If so, I prefer you recommending me a better solution and adding that to your source code.

**Comment by ryanss** [comment]
One potential problem I see with your mapping is that it saves articles to the same file which will prevent you from saving more than one article at a time. I'm not sure a mapping is necessary for this, it's pretty easy to just use `:w my_dir/article_name.md` when you want to save an article. Adding this feature to the source code would be problematic because a global setting would have to be added to configure what directory the article would save to.

Personally, I just use `Shift+O` to open the article in my browser and use the `Add to Reading List` feature of the browser when I want to revisit an article or comments page later.

**Comment by eduOS** [comment]
Great! Thanks. As an aside, the file name is not .md, it's only the suffix of every file.
