### ISSUE TITLE
Allow mapping to directly open the news link in browser

### ISSUE THREAD

**Issue by sagarjauhari** [ryanss/vim-hackernews#4]
Not the HN Thread link but the actual news link.

Also, if #12 is fixed, the mapping above could be implemented using an ignored 'url' along with (after/before) the ignored 'item-id' so that its never visible to the user but can be used to open the news link.

**Comment by gingerlime** [comment]
+1

**Comment by ryanss** [comment]
I agree this would be a nice addition. I have two ideas to implement this and I'm not sure which is better:

1. Pressing `o`/`O` on the first line (with the title and domain) opens the actual link while pressing `o`/`O` on the line with the points, username and comments opens the comments page. This is similar to how the actual website works.
2. Introduce a new map key that opens the actual link. So pressing `o`/`O` on either of the lines of the story would open the comments page, pressing `i` would open the story url in Vim, and pressing `I` would open the story url in the default web browser.

The advantage of (1) is that the key maps remain consistent on all pages. If `i`/`I` are introduced what do they do on an url in a comment? However, (1) also makes adding shortcuts to move between stories worse because just moving to the first line of a story is not enough to get to the comments page.

I'd love to get input from others.

**Comment by gingerlime** [comment]
My 2 cents: The first option sounds a bit more intuitive and you have less keyboard-shortcuts to remember. I agree that it fits with the normal HN browsing 'workflow' where you decide where to click to either view the story or the comments.

**Comment by sagarjauhari** [comment]
+1
My vote would go for option 1.
